controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_formulaire_signature_confirmation:
    path: /formulaire/sign/confirmation/{id}/{token}
    controller: App\Controller\FormulaireController::signatureConfirmation
    methods: GET
